### ISSUE TITLE
timer minutes

### ISSUE THREAD

**Issue by sure1243jupiter** [michaeljstevens/react-native-stopwatch-timer#15] opened 2018-05-26 07:43 UTC
hi there it is better to get the individual seconds and minutes from getTime instead of getting a formatted value from it

**Comment by janguck** [comment] 2018-07-11 20:29
how get?

**Comment by michaeljstevens** [comment] 2019-06-16 09:52
@sure1243jupiter latest version includes getMsecs function

**Comment by michaeljstevens** [comment] 2019-06-16 09:52
@johnlow95 duplicate of #18

**Closed by michaeljstevens** 2019-06-16 09:52 UTC

**Comment by shubhamtechvalens** [comment] 2019-07-08 06:35
@michaeljstevens I am using getMsecs function to get the time. Can you please help me with accessing value outside the function?

I am using just like this:

  getFormattedTime (time) {
    if (time !== 0) {
      this.milliSeconds = time
      console.log('getFormattedTime', this.milliSeconds)
    }
  }

just after this method variable milliSeconds reset to its initial value i.e. 0.
How can i access milliSeconds outside getFormattedTime?
